vim.cmd([[ set number]])
vim.cmd([[ set noswapfile ]])
vim.cmd([[ set ignorecase ]])
vim.cmd([[ set incsearch ]])
vim.cmd([[ set cursorline ]])
vim.cmd([[ set hlsearch ]])
vim.cmd([[ let g:coq_settings = { 'auto_start' : 'shut-up' } ]])
-- vim.cmd([[ let mapleader = "\"]])
vim.cmd([[ colorscheme tokyonight-night ]])
vim.cmd([[ nnoremap <leader>v <cmd>NvimTreeToggle<cr> ]])
vim.cmd([[ inoremap jk <ESC> ]])

